### ISSUE TITLE
[FEATURE] Base64 Based Challenge

### ISSUE THREAD

**Issue by lennis-dev** [lennis-dev/hackit#32]
### Discussed in https://github.com/lennis-dev/hackit/discussions/31

<div type='discussions-op-text'>

<sup>Originally posted by **aashu10sh** October 18, 2024</sup>
### Is there an existing discussion for this?

- [X] I have searched the existing discussions

### Describe your idea

I was thinking of a challenge where we can introduce the users to base64 encoding. It would be similar to the 'easy-beginning' challenge, here they'd have to look at the JavaScript source code and decode the base64 being compared ( to users input)  to find the correct solution. 

More Detail:
Name : "Basic Challenge"
Description: " I heard there's a technique for encoding files safely in the web, something 64?"

### Anything else?

This is my first ever open source contribution ( attempt ). I hope you understood what I am trying to say:)
 </div>

**Comment by lennis-dev** [comment]
@aashu10sh you have to write something in the conversation so that I can assign you. If you need help, feel free to ask

**Comment by aashu10sh** [comment]
@lennis-dev Yo! Could you please assign me the issue.
